# Generated by Django 5.0.4 on 2024-04-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='is_block',
        ),
        migrations.AddField(
            model_name='council',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
